
## Data Preprocessing
---

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import kagglehub
path = kagglehub.dataset_download("novandraanugrah/bitcoin-historical-datasets-2018-2024")

Using Colab cache for faster access to the 'bitcoin-historical-datasets-2018-2024' dataset.

In [ ]:
import os

print(os.listdir(path))

['btc_1h_data_2018_to_2025.csv', 'btc_15m_data_2018_to_2025.csv', 'btc_4h_data_2018_to_2025.csv', 'btc_1d_data_2018_to_2025.csv']

In [ ]:

df_15m = pd.read_csv(path + "/btc_15m_data_2018_to_2025.csv")
df_1h  = pd.read_csv(path + "/btc_1h_data_2018_to_2025.csv")
df_4h  = pd.read_csv(path + "/btc_4h_data_2018_to_2025.csv")
df_1d  = pd.read_csv(path + "/btc_1d_data_2018_to_2025.csv")

In [ ]:
df_15m["timeframe"] = "15m"
df_1h["timeframe"]  = "1h"
df_4h["timeframe"]  = "4h"
df_1d["timeframe"]  = "1d"

In [ ]:
df = pd.concat([df_15m, df_1h, df_4h, df_1d], ignore_index=True)

In [ ]:
df["Open time"] = pd.to_datetime(df["Open time"], format="mixed", utc=True)
df["Close time"] = pd.to_datetime(df["Close time"], format="mixed", utc=True)

In [ ]:
df = df.sort_values("Open time").reset_index(drop=True)

In [ ]:
df.head(50)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore,timeframe
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,8.576108e+05,0,15m
1,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,9.937537e+06,0,4h
2,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,5.280975e+07,0,1d
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,3.090541e+06,0,1h
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,6.422812e+05,0,15m
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,5.900347e+05,0,15m
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,1.000614e+06,0,15m
7,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,4.618369e+05,0,15m
8,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,2.430449e+06,0,1h
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,6.111437e+05,0,15m
10,2018-01-01 01:30:00+00:00,13559.99,13559.99,13430.00,13440.01,74.368405,2018-01-01 01:44:59.999000+00:00,1.004038e+06,1047,38.653471,5.219765e+05,0,15m
11,2018-01-01 01:45:00+00:00,13440.01,13440.01,13155.38,13203.06,148.929310,2018-01-01 01:59:59.999000+00:00,1.982724e+06,1650,62.793323,8.354925e+05,0,15m
12,2018-01-01 02:00:00+00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999000+00:00,5.710192e+06,4887,192.237935,2.558505e+06,0,1h
13,2018-01-01 02:00:00+00:00,13203.00,13411.76,13202.03,13387.00,108.542470,2018-01-01 02:14:59.999000+00:00,1.446924e+06,1528,40.703069,5.424858e+05,0,15m
14,2018-01-01 02:15:00+00:00,13387.00,13388.00,13225.00,13225.00,95.186039,2018-01-01 02:29:59.999000+00:00,1.265431e+06,1079,43.068838,5.726181e+05,0,15m
15,2018-01-01 02:30:00+00:00,13247.80,13349.99,13200.00,13321.08,111.719503,2018-01-01 02:44:59.999000+00:00,1.483295e+06,1074,53.247854,7.073543e+05,0,15m
16,2018-01-01 02:45:00+00:00,13338.97,13418.43,13260.09,13330.18,113.616560,2018-01-01 02:59:59.999000+00:00,1.514541e+06,1206,55.218174,7.360464e+05,0,15m
17,2018-01-01 03:00:00+00:00,13330.26,13450.76,13290.00,13444.99,89.019514,2018-01-01 03:14:59.999000+00:00,1.189070e+06,1070,35.514692,4.747012e+05,0,15m
18,2018-01-01 03:00:00+00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999000+00:00,5.657448e+06,4789,137.918407,1.858041e+06,0,1h
19,2018-01-01 03:15:00+00:00,13440.00,13611.27,13440.00,13562.37,112.273306,2018-01-01 03:29:59.999000+00:00,1.516663e+06,1415,43.355251,5.859573e+05,0,15m
20,2018-01-01 03:30:00+00:00,13562.37,13611.01,13400.00,13500.00,105.619306,2018-01-01 03:44:59.999000+00:00,1.428926e+06,1051,32.728398,4.433612e+05,0,15m
21,2018-01-01 03:45:00+00:00,13510.00,13510.00,13400.04,13410.03,113.174904,2018-01-01 03:59:59.999000+00:00,1.522789e+06,1253,26.320066,3.540215e+05,0,15m
22,2018-01-01 04:00:00+00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999000+00:00,4.588047e+06,4563,172.957635,2.328058e+06,0,1h
23,2018-01-01 04:00:00+00:00,13434.98,13818.55,13322.15,13570.35,1302.214836,2018-01-01 07:59:59.999000+00:00,1.770254e+07,18061,588.516222,7.998796e+06,0,4h
24,2018-01-01 04:00:00+00:00,13434.98,13483.07,13322.15,13351.71,94.759633,2018-01-01 04:14:59.999000+00:00,1.271041e+06,1255,34.071009,4.567588e+05,0,15m
25,2018-01-01 04:15:00+00:00,13354.99,13449.89,13323.55,13430.00,70.563137,2018-01-01 04:29:59.999000+00:00,9.432340e+05,1022,42.572089,5.691023e+05,0,15m
26,2018-01-01 04:30:00+00:00,13429.99,13550.00,13401.94,13507.41,68.943608,2018-01-01 04:44:59.999000+00:00,9.290333e+05,1006,45.665955,6.153539e+05,0,15m
27,2018-01-01 04:45:00+00:00,13507.41,13623.29,13465.41,13601.01,106.540951,2018-01-01 04:59:59.999000+00:00,1.444739e+06,1280,50.648582,6.868429e+05,0,15m
28,2018-01-01 05:00:00+00:00,13615.20,13677.83,13552.02,13627.14,185.935937,2018-01-01 05:14:59.999000+00:00,2.534197e+06,2119,49.916113,6.803406e+05,0,15m
29,2018-01-01 05:00:00+00:00,13615.20,13699.00,13526.50,13558.99,404.229046,2018-01-01 05:59:59.999000+00:00,5.499055e+06,5086,142.331058,1.935710e+06,0,1h
30,2018-01-01 05:15:00+00:00,13600.00,13699.00,13532.57,13618.51,103.502867,2018-01-01 05:29:59.999000+00:00,1.408949e+06,1213,45.980964,6.259618e+05,0,15m
31,2018-01-01 05:30:00+00:00,13618.51,13629.00,13530.00,13580.01,70.523393,2018-01-01 05:44:59.999000+00:00,9.562368e+05,925,27.705653,3.756632e+05,0,15m
32,2018-01-01 05:45:00+00:00,13558.95,13600.00,13526.50,13558.99,44.266849,2018-01-01 05:59:59.999000+00:00,5.996720e+05,829,18.728328,2.537446e+05,0,15m
33,2018-01-01 06:00:00+00:00,13539.00,13571.63,13510.00,13532.32,58.377845,2018-01-01 06:14:59.999000+00:00,7.899298e+05,863,20.938556,2.833936e+05,0,15m
34,2018-01-01 06:00:00+00:00,13539.00,13800.00,13510.00,13780.41,264.989684,2018-01-01 06:59:59.999000+00:00,3.613408e+06,4072,126.077500,1.718753e+06,0,1h
35,2018-01-01 06:15:00+00:00,13532.00,13701.13,13510.51,13687.76,99.588918,2018-01-01 06:29:59.999000+00:00,1.355583e+06,1275,59.744662,8.124585e+05,0,15m
36,2018-01-01 06:30:00+00:00,13687.76,13750.00,13620.01,13722.47,52.257108,2018-01-01 06:44:59.999000+00:00,7.143783e+05,997,20.579891,2.814531e+05,0,15m
37,2018-01-01 06:45:00+00:00,13722.48,13800.00,13702.10,13780.41,54.765813,2018-01-01 06:59:59.999000+00:00,7.535164e+05,937,24.814391,3.414476e+05,0,15m
38,2018-01-01 07:00:00+00:00,13780.00,13818.55,13555.02,13570.35,292.188777,2018-01-01 07:59:59.999000+00:00,4.002026e+06,4340,147.150029,2.016275e+06,0,1h
39,2018-01-01 07:00:00+00:00,13780.00,13818.55,13670.00,13775.00,84.038319,2018-01-01 07:14:59.999000+00:00,1.157374e+06,1319,42.535515,5.858475e+05,0,15m
40,2018-01-01 07:15:00+00:00,13774.99,13775.99,13600.00,13698.00,74.453320,2018-01-01 07:29:59.999000+00:00,1.019043e+06,1312,41.686674,5.707639e+05,0,15m
41,2018-01-01 07:30:00+00:00,13698.00,13775.00,13590.00,13644.95,89.776654,2018-01-01 07:44:59.999000+00:00,1.228408e+06,895,41.665985,5.703255e+05,0,15m
42,2018-01-01 07:45:00+00:00,13644.97,13659.97,13555.02,13570.35,43.920484,2018-01-01 07:59:59.999000+00:00,5.972011e+05,814,21.261855,2.893379e+05,0,15m
43,2018-01-01 08:00:00+00:00,13569.98,13735.24,13400.00,13499.99,271.813553,2018-01-01 08:59:59.999000+00:00,3.681944e+06,3733,122.809696,1.664737e+06,0,1h
44,2018-01-01 08:00:00+00:00,13569.98,13735.24,13001.13,13220.56,1319.755931,2018-01-01 11:59:59.999000+00:00,1.765121e+07,17200,582.668293,7.792109e+06,0,4h
45,2018-01-01 08:00:00+00:00,13569.98,13665.00,13520.00,13656.23,58.542067,2018-01-01 08:14:59.999000+00:00,7.948098e+05,919,20.562018,2.791373e+05,0,15m
46,2018-01-01 08:15:00+00:00,13656.23,13735.24,13610.27,13632.89,58.900513,2018-01-01 08:29:59.999000+00:00,8.054309e+05,869,34.862743,4.767699e+05,0,15m
47,2018-01-01 08:30:00+00:00,13614.33,13649.96,13400.00,13434.71,104.766871,2018-01-01 08:44:59.999000+00:00,1.413295e+06,1204,46.829395,6.318254e+05,0,15m
48,2018-01-01 08:45:00+00:00,13415.00,13508.69,13414.76,13499.99,49.604102,2018-01-01 08:59:59.999000+00:00,6.684083e+05,741,20.555540,2.770044e+05,0,15m
49,2018-01-01 09:00:00+00:00,13499.97,13599.98,13459.11,13589.83,55.827255,2018-01-01 09:14:59.999000+00:00,7.554221e+05,825,24.819559,3.360020e+05,0,15m

In [ ]:
df = df.drop(columns=["Ignore"])

In [ ]:
df["year"] = df["Open time"].dt.year
df["month"] = df["Open time"].dt.month
df["day"] = df["Open time"].dt.day

df["quarter"] = df["Open time"].dt.quarter

In [ ]:
df[["year","month","day","quarter"]].isna().sum()

year       3
month      3
day        3
quarter    3
dtype: int64

In [ ]:
df[df.isna().any(axis=1)].head()

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,timeframe,year,month,day,quarter
379823,NaT,72479.05,72747.22,72420.44,72701.07,210.80346,NaT,1.529591e+07,60760,108.91938,7.904695e+06,15m,NaN,NaN,NaN,NaN
379824,NaT,72109.59,73081.77,71725.74,72749.44,1471.44945,NaT,1.065980e+08,312854,860.63713,6.236168e+07,1h,NaN,NaN,NaN,NaN
379825,NaT,71481.24,71989.93,71320.08,71549.94,1241.12480,NaT,8.881007e+07,346610,689.21644,4.931554e+07,4h,NaN,NaN,NaN,NaN

In [ ]:
df = df.dropna(subset=["Open time"])
df = df.reset_index(drop=True)

In [ ]:
df["year"] = df["Open time"].dt.year.astype(int)
df["month"] = df["Open time"].dt.month.astype(int)
df["day"] = df["Open time"].dt.day.astype(int)
df["quarter"] = df["Open time"].dt.quarter.astype(int)

In [ ]:
df.head(50)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,timeframe,year,month,day,quarter
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,8.576108e+05,15m,2018,1,1,1
1,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,9.937537e+06,4h,2018,1,1,1
2,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,5.280975e+07,1d,2018,1,1,1
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,3.090541e+06,1h,2018,1,1,1
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,6.422812e+05,15m,2018,1,1,1
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,5.900347e+05,15m,2018,1,1,1
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,1.000614e+06,15m,2018,1,1,1
7,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,4.618369e+05,15m,2018,1,1,1
8,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,2.430449e+06,1h,2018,1,1,1
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,6.111437e+05,15m,2018,1,1,1
10,2018-01-01 01:30:00+00:00,13559.99,13559.99,13430.00,13440.01,74.368405,2018-01-01 01:44:59.999000+00:00,1.004038e+06,1047,38.653471,5.219765e+05,15m,2018,1,1,1
11,2018-01-01 01:45:00+00:00,13440.01,13440.01,13155.38,13203.06,148.929310,2018-01-01 01:59:59.999000+00:00,1.982724e+06,1650,62.793323,8.354925e+05,15m,2018,1,1,1
12,2018-01-01 02:00:00+00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999000+00:00,5.710192e+06,4887,192.237935,2.558505e+06,1h,2018,1,1,1
13,2018-01-01 02:00:00+00:00,13203.00,13411.76,13202.03,13387.00,108.542470,2018-01-01 02:14:59.999000+00:00,1.446924e+06,1528,40.703069,5.424858e+05,15m,2018,1,1,1
14,2018-01-01 02:15:00+00:00,13387.00,13388.00,13225.00,13225.00,95.186039,2018-01-01 02:29:59.999000+00:00,1.265431e+06,1079,43.068838,5.726181e+05,15m,2018,1,1,1
15,2018-01-01 02:30:00+00:00,13247.80,13349.99,13200.00,13321.08,111.719503,2018-01-01 02:44:59.999000+00:00,1.483295e+06,1074,53.247854,7.073543e+05,15m,2018,1,1,1
16,2018-01-01 02:45:00+00:00,13338.97,13418.43,13260.09,13330.18,113.616560,2018-01-01 02:59:59.999000+00:00,1.514541e+06,1206,55.218174,7.360464e+05,15m,2018,1,1,1
17,2018-01-01 03:00:00+00:00,13330.26,13450.76,13290.00,13444.99,89.019514,2018-01-01 03:14:59.999000+00:00,1.189070e+06,1070,35.514692,4.747012e+05,15m,2018,1,1,1
18,2018-01-01 03:00:00+00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999000+00:00,5.657448e+06,4789,137.918407,1.858041e+06,1h,2018,1,1,1
19,2018-01-01 03:15:00+00:00,13440.00,13611.27,13440.00,13562.37,112.273306,2018-01-01 03:29:59.999000+00:00,1.516663e+06,1415,43.355251,5.859573e+05,15m,2018,1,1,1
20,2018-01-01 03:30:00+00:00,13562.37,13611.01,13400.00,13500.00,105.619306,2018-01-01 03:44:59.999000+00:00,1.428926e+06,1051,32.728398,4.433612e+05,15m,2018,1,1,1
21,2018-01-01 03:45:00+00:00,13510.00,13510.00,13400.04,13410.03,113.174904,2018-01-01 03:59:59.999000+00:00,1.522789e+06,1253,26.320066,3.540215e+05,15m,2018,1,1,1
22,2018-01-01 04:00:00+00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999000+00:00,4.588047e+06,4563,172.957635,2.328058e+06,1h,2018,1,1,1
23,2018-01-01 04:00:00+00:00,13434.98,13818.55,13322.15,13570.35,1302.214836,2018-01-01 07:59:59.999000+00:00,1.770254e+07,18061,588.516222,7.998796e+06,4h,2018,1,1,1
24,2018-01-01 04:00:00+00:00,13434.98,13483.07,13322.15,13351.71,94.759633,2018-01-01 04:14:59.999000+00:00,1.271041e+06,1255,34.071009,4.567588e+05,15m,2018,1,1,1
25,2018-01-01 04:15:00+00:00,13354.99,13449.89,13323.55,13430.00,70.563137,2018-01-01 04:29:59.999000+00:00,9.432340e+05,1022,42.572089,5.691023e+05,15m,2018,1,1,1
26,2018-01-01 04:30:00+00:00,13429.99,13550.00,13401.94,13507.41,68.943608,2018-01-01 04:44:59.999000+00:00,9.290333e+05,1006,45.665955,6.153539e+05,15m,2018,1,1,1
27,2018-01-01 04:45:00+00:00,13507.41,13623.29,13465.41,13601.01,106.540951,2018-01-01 04:59:59.999000+00:00,1.444739e+06,1280,50.648582,6.868429e+05,15m,2018,1,1,1
28,2018-01-01 05:00:00+00:00,13615.20,13677.83,13552.02,13627.14,185.935937,2018-01-01 05:14:59.999000+00:00,2.534197e+06,2119,49.916113,6.803406e+05,15m,2018,1,1,1
29,2018-01-01 05:00:00+00:00,13615.20,13699.00,13526.50,13558.99,404.229046,2018-01-01 05:59:59.999000+00:00,5.499055e+06,5086,142.331058,1.935710e+06,1h,2018,1,1,1
30,2018-01-01 05:15:00+00:00,13600.00,13699.00,13532.57,13618.51,103.502867,2018-01-01 05:29:59.999000+00:00,1.408949e+06,1213,45.980964,6.259618e+05,15m,2018,1,1,1
31,2018-01-01 05:30:00+00:00,13618.51,13629.00,13530.00,13580.01,70.523393,2018-01-01 05:44:59.999000+00:00,9.562368e+05,925,27.705653,3.756632e+05,15m,2018,1,1,1
32,2018-01-01 05:45:00+00:00,13558.95,13600.00,13526.50,13558.99,44.266849,2018-01-01 05:59:59.999000+00:00,5.996720e+05,829,18.728328,2.537446e+05,15m,2018,1,1,1
33,2018-01-01 06:00:00+00:00,13539.00,13571.63,13510.00,13532.32,58.377845,2018-01-01 06:14:59.999000+00:00,7.899298e+05,863,20.938556,2.833936e+05,15m,2018,1,1,1
34,2018-01-01 06:00:00+00:00,13539.00,13800.00,13510.00,13780.41,264.989684,2018-01-01 06:59:59.999000+00:00,3.613408e+06,4072,126.077500,1.718753e+06,1h,2018,1,1,1
35,2018-01-01 06:15:00+00:00,13532.00,13701.13,13510.51,13687.76,99.588918,2018-01-01 06:29:59.999000+00:00,1.355583e+06,1275,59.744662,8.124585e+05,15m,2018,1,1,1
36,2018-01-01 06:30:00+00:00,13687.76,13750.00,13620.01,13722.47,52.257108,2018-01-01 06:44:59.999000+00:00,7.143783e+05,997,20.579891,2.814531e+05,15m,2018,1,1,1
37,2018-01-01 06:45:00+00:00,13722.48,13800.00,13702.10,13780.41,54.765813,2018-01-01 06:59:59.999000+00:00,7.535164e+05,937,24.814391,3.414476e+05,15m,2018,1,1,1
38,2018-01-01 07:00:00+00:00,13780.00,13818.55,13555.02,13570.35,292.188777,2018-01-01 07:59:59.999000+00:00,4.002026e+06,4340,147.150029,2.016275e+06,1h,2018,1,1,1
39,2018-01-01 07:00:00+00:00,13780.00,13818.55,13670.00,13775.00,84.038319,2018-01-01 07:14:59.999000+00:00,1.157374e+06,1319,42.535515,5.858475e+05,15m,2018,1,1,1
40,2018-01-01 07:15:00+00:00,13774.99,13775.99,13600.00,13698.00,74.453320,2018-01-01 07:29:59.999000+00:00,1.019043e+06,1312,41.686674,5.707639e+05,15m,2018,1,1,1
41,2018-01-01 07:30:00+00:00,13698.00,13775.00,13590.00,13644.95,89.776654,2018-01-01 07:44:59.999000+00:00,1.228408e+06,895,41.665985,5.703255e+05,15m,2018,1,1,1
42,2018-01-01 07:45:00+00:00,13644.97,13659.97,13555.02,13570.35,43.920484,2018-01-01 07:59:59.999000+00:00,5.972011e+05,814,21.261855,2.893379e+05,15m,2018,1,1,1
43,2018-01-01 08:00:00+00:00,13569.98,13735.24,13400.00,13499.99,271.813553,2018-01-01 08:59:59.999000+00:00,3.681944e+06,3733,122.809696,1.664737e+06,1h,2018,1,1,1
44,2018-01-01 08:00:00+00:00,13569.98,13735.24,13001.13,13220.56,1319.755931,2018-01-01 11:59:59.999000+00:00,1.765121e+07,17200,582.668293,7.792109e+06,4h,2018,1,1,1
45,2018-01-01 08:00:00+00:00,13569.98,13665.00,13520.00,13656.23,58.542067,2018-01-01 08:14:59.999000+00:00,7.948098e+05,919,20.562018,2.791373e+05,15m,2018,1,1,1
46,2018-01-01 08:15:00+00:00,13656.23,13735.24,13610.27,13632.89,58.900513,2018-01-01 08:29:59.999000+00:00,8.054309e+05,869,34.862743,4.767699e+05,15m,2018,1,1,1
47,2018-01-01 08:30:00+00:00,13614.33,13649.96,13400.00,13434.71,104.766871,2018-01-01 08:44:59.999000+00:00,1.413295e+06,1204,46.829395,6.318254e+05,15m,2018,1,1,1
48,2018-01-01 08:45:00+00:00,13415.00,13508.69,13414.76,13499.99,49.604102,2018-01-01 08:59:59.999000+00:00,6.684083e+05,741,20.555540,2.770044e+05,15m,2018,1,1,1
49,2018-01-01 09:00:00+00:00,13499.97,13599.98,13459.11,13589.83,55.827255,2018-01-01 09:14:59.999000+00:00,7.554221e+05,825,24.819559,3.360020e+05,15m,2018,1,1,1

In [ ]:
df.isna().sum()

Open time                       0
Open                            0
High                            0
Low                             0
Close                           0
Volume                          0
Close time                      0
Quote asset volume              0
Number of trades                0
Taker buy base asset volume     0
Taker buy quote asset volume    0
timeframe                       0
year                            0
month                           0
day                             0
quarter                         0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.duplicated(subset=["Open time","timeframe"]).sum()

np.int64(6)

In [ ]:
df[df.duplicated(subset=["Open time","timeframe"], keep=False)]

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,timeframe,year,month,day,quarter
23341,2018-07-06 00:00:00+00:00,6529.20,6553.00,6511.00,6530.00,4120.321071,2018-07-06 03:59:59.999000+00:00,2.690673e+07,24305,2337.061505,1.526290e+07,4h,2018,7,6,3
23343,2018-07-06 00:00:00+00:00,108700.00,109111.00,108518.83,108888.00,1086.391210,2018-07-06 03:59:59.999000+00:00,1.182862e+08,214025,508.738310,5.538955e+07,4h,2018,7,6,3
23363,2018-07-06 04:00:00+00:00,108888.00,108978.64,107505.00,107573.29,3616.089460,2018-07-06 07:59:59.999000+00:00,3.905847e+08,627971,1611.098070,1.740189e+08,4h,2018,7,6,3
23364,2018-07-06 04:00:00+00:00,6530.00,6533.63,6425.00,6478.85,5824.504486,2018-07-06 07:59:59.999000+00:00,3.778332e+07,37316,3043.078755,1.974576e+07,4h,2018,7,6,3
23469,2018-07-07 00:00:00+00:00,6609.79,6613.99,6581.05,6596.93,766.671591,2018-07-07 00:59:59.999000+00:00,5.055038e+06,6145,417.287181,2.751863e+06,1h,2018,7,7,3
23471,2018-07-07 00:00:00+00:00,107469.22,107813.04,107440.63,107692.01,228.631950,2018-07-07 00:59:59.999000+00:00,2.461733e+07,42593,138.742240,1.493892e+07,1h,2018,7,7,3
23478,2018-07-07 01:00:00+00:00,6596.93,6600.00,6561.01,6566.01,887.436249,2018-07-07 01:59:59.999000+00:00,5.837711e+06,6193,488.621779,3.214876e+06,1h,2018,7,7,3
23479,2018-07-07 01:00:00+00:00,107692.01,107941.99,107689.91,107911.20,255.841360,2018-07-07 01:59:59.999000+00:00,2.757870e+07,33521,129.597780,1.397040e+07,1h,2018,7,7,3
23504,2018-07-07 06:00:00+00:00,108254.95,108254.96,108090.24,108115.55,64.056100,2018-07-07 06:14:59.999000+00:00,6.927307e+06,10111,21.874150,2.365207e+06,15m,2018,7,7,3
23505,2018-07-07 06:00:00+00:00,6598.00,6600.00,6592.88,6592.90,184.610237,2018-07-07 06:14:59.999000+00:00,1.217864e+06,924,73.630565,4.857697e+05,15m,2018,7,7,3
23507,2018-07-07 06:15:00+00:00,108115.55,108130.80,108057.35,108104.01,41.816480,2018-07-07 06:29:59.999000+00:00,4.519670e+06,9175,21.072920,2.277494e+06,15m,2018,7,7,3
23508,2018-07-07 06:15:00+00:00,6592.90,6592.90,6572.01,6583.30,184.209006,2018-07-07 06:29:59.999000+00:00,1.212812e+06,1483,90.503658,5.958897e+05,15m,2018,7,7,3

In [ ]:
df = df.sort_values("Number of trades", ascending=False)
df = df.drop_duplicates(subset=["Open time","timeframe"], keep="first")
df = df.sort_values("Open time")
df = df.reset_index(drop=True)

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
df.dtypes

Open time                       datetime64[ns, UTC]
Open                                        float64
High                                        float64
Low                                         float64
Close                                       float64
Volume                                      float64
Close time                      datetime64[ns, UTC]
Quote asset volume                          float64
Number of trades                              int64
Taker buy base asset volume                 float64
Taker buy quote asset volume                float64
timeframe                                    object
year                                          int64
month                                         int64
day                                           int64
quarter                                       int64
dtype: object

In [ ]:
(df[["Open","High","Low","Close","Volume"]] < 0).sum()

Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

## Feature Engnineering

#price

In [ ]:
#price movement

df['price_change'] = df['Close'] - df['Open']

In [ ]:
# Return
df['return_pct'] = df['price_change'] / df['Open']

In [ ]:
# Volatility
df['volatility'] = df['High'] - df['Low']

In [ ]:
df.head(50)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,timeframe,year,month,day,quarter,price_change,return_pct,volatility
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,3.090541e+06,1h,2018,1,1,1,-186.64,-0.013608,315.64
1,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,5.280975e+07,1d,2018,1,1,1,-335.65,-0.024472,1068.55
2,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,9.937537e+06,4h,2018,1,1,1,-305.62,-0.022283,560.27
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,8.576108e+05,15m,2018,1,1,1,-159.50,-0.011629,315.64
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,6.422812e+05,15m,2018,1,1,1,-12.63,-0.000933,148.87
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,5.900347e+05,15m,2018,1,1,1,-29.59,-0.002192,95.37
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,1.000614e+06,15m,2018,1,1,1,34.36,0.002546,240.87
7,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,2.430449e+06,1h,2018,1,1,1,-325.93,-0.024091,440.51
8,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,4.618369e+05,15m,2018,1,1,1,-83.36,-0.006162,169.46
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,6.111437e+05,15m,2018,1,1,1,90.01,0.006682,150.26
10,2018-01-01 01:30:00+00:00,13559.99,13559.99,13430.00,13440.01,74.368405,2018-01-01 01:44:59.999000+00:00,1.004038e+06,1047,38.653471,5.219765e+05,15m,2018,1,1,1,-119.98,-0.008848,129.99
11,2018-01-01 01:45:00+00:00,13440.01,13440.01,13155.38,13203.06,148.929310,2018-01-01 01:59:59.999000+00:00,1.982724e+06,1650,62.793323,8.354925e+05,15m,2018,1,1,1,-236.95,-0.017630,284.63
12,2018-01-01 02:00:00+00:00,13203.00,13411.76,13202.03,13387.00,108.542470,2018-01-01 02:14:59.999000+00:00,1.446924e+06,1528,40.703069,5.424858e+05,15m,2018,1,1,1,184.00,0.013936,209.73
13,2018-01-01 02:00:00+00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999000+00:00,5.710192e+06,4887,192.237935,2.558505e+06,1h,2018,1,1,1,127.18,0.009633,218.43
14,2018-01-01 02:15:00+00:00,13387.00,13388.00,13225.00,13225.00,95.186039,2018-01-01 02:29:59.999000+00:00,1.265431e+06,1079,43.068838,5.726181e+05,15m,2018,1,1,1,-162.00,-0.012101,163.00
15,2018-01-01 02:30:00+00:00,13247.80,13349.99,13200.00,13321.08,111.719503,2018-01-01 02:44:59.999000+00:00,1.483295e+06,1074,53.247854,7.073543e+05,15m,2018,1,1,1,73.28,0.005531,149.99
16,2018-01-01 02:45:00+00:00,13338.97,13418.43,13260.09,13330.18,113.616560,2018-01-01 02:59:59.999000+00:00,1.514541e+06,1206,55.218174,7.360464e+05,15m,2018,1,1,1,-8.79,-0.000659,158.34
17,2018-01-01 03:00:00+00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999000+00:00,5.657448e+06,4789,137.918407,1.858041e+06,1h,2018,1,1,1,79.77,0.005984,321.27
18,2018-01-01 03:00:00+00:00,13330.26,13450.76,13290.00,13444.99,89.019514,2018-01-01 03:14:59.999000+00:00,1.189070e+06,1070,35.514692,4.747012e+05,15m,2018,1,1,1,114.73,0.008607,160.76
19,2018-01-01 03:15:00+00:00,13440.00,13611.27,13440.00,13562.37,112.273306,2018-01-01 03:29:59.999000+00:00,1.516663e+06,1415,43.355251,5.859573e+05,15m,2018,1,1,1,122.37,0.009105,171.27
20,2018-01-01 03:30:00+00:00,13562.37,13611.01,13400.00,13500.00,105.619306,2018-01-01 03:44:59.999000+00:00,1.428926e+06,1051,32.728398,4.433612e+05,15m,2018,1,1,1,-62.37,-0.004599,211.01
21,2018-01-01 03:45:00+00:00,13510.00,13510.00,13400.04,13410.03,113.174904,2018-01-01 03:59:59.999000+00:00,1.522789e+06,1253,26.320066,3.540215e+05,15m,2018,1,1,1,-99.97,-0.007400,109.96
22,2018-01-01 04:00:00+00:00,13434.98,13818.55,13322.15,13570.35,1302.214836,2018-01-01 07:59:59.999000+00:00,1.770254e+07,18061,588.516222,7.998796e+06,4h,2018,1,1,1,135.37,0.010076,496.40
23,2018-01-01 04:00:00+00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999000+00:00,4.588047e+06,4563,172.957635,2.328058e+06,1h,2018,1,1,1,166.03,0.012358,301.14
24,2018-01-01 04:00:00+00:00,13434.98,13483.07,13322.15,13351.71,94.759633,2018-01-01 04:14:59.999000+00:00,1.271041e+06,1255,34.071009,4.567588e+05,15m,2018,1,1,1,-83.27,-0.006198,160.92
25,2018-01-01 04:15:00+00:00,13354.99,13449.89,13323.55,13430.00,70.563137,2018-01-01 04:29:59.999000+00:00,9.432340e+05,1022,42.572089,5.691023e+05,15m,2018,1,1,1,75.01,0.005617,126.34
26,2018-01-01 04:30:00+00:00,13429.99,13550.00,13401.94,13507.41,68.943608,2018-01-01 04:44:59.999000+00:00,9.290333e+05,1006,45.665955,6.153539e+05,15m,2018,1,1,1,77.42,0.005765,148.06
27,2018-01-01 04:45:00+00:00,13507.41,13623.29,13465.41,13601.01,106.540951,2018-01-01 04:59:59.999000+00:00,1.444739e+06,1280,50.648582,6.868429e+05,15m,2018,1,1,1,93.60,0.006930,157.88
28,2018-01-01 05:00:00+00:00,13615.20,13677.83,13552.02,13627.14,185.935937,2018-01-01 05:14:59.999000+00:00,2.534197e+06,2119,49.916113,6.803406e+05,15m,2018,1,1,1,11.94,0.000877,125.81
29,2018-01-01 05:00:00+00:00,13615.20,13699.00,13526.50,13558.99,404.229046,2018-01-01 05:59:59.999000+00:00,5.499055e+06,5086,142.331058,1.935710e+06,1h,2018,1,1,1,-56.21,-0.004128,172.50
30,2018-01-01 05:15:00+00:00,13600.00,13699.00,13532.57,13618.51,103.502867,2018-01-01 05:29:59.999000+00:00,1.408949e+06,1213,45.980964,6.259618e+05,15m,2018,1,1,1,18.51,0.001361,166.43
31,2018-01-01 05:30:00+00:00,13618.51,13629.00,13530.00,13580.01,70.523393,2018-01-01 05:44:59.999000+00:00,9.562368e+05,925,27.705653,3.756632e+05,15m,2018,1,1,1,-38.50,-0.002827,99.00
32,2018-01-01 05:45:00+00:00,13558.95,13600.00,13526.50,13558.99,44.266849,2018-01-01 05:59:59.999000+00:00,5.996720e+05,829,18.728328,2.537446e+05,15m,2018,1,1,1,0.04,0.000003,73.50
33,2018-01-01 06:00:00+00:00,13539.00,13571.63,13510.00,13532.32,58.377845,2018-01-01 06:14:59.999000+00:00,7.899298e+05,863,20.938556,2.833936e+05,15m,2018,1,1,1,-6.68,-0.000493,61.63
34,2018-01-01 06:00:00+00:00,13539.00,13800.00,13510.00,13780.41,264.989684,2018-01-01 06:59:59.999000+00:00,3.613408e+06,4072,126.077500,1.718753e+06,1h,2018,1,1,1,241.41,0.017831,290.00
35,2018-01-01 06:15:00+00:00,13532.00,13701.13,13510.51,13687.76,99.588918,2018-01-01 06:29:59.999000+00:00,1.355583e+06,1275,59.744662,8.124585e+05,15m,2018,1,1,1,155.76,0.011510,190.62
36,2018-01-01 06:30:00+00:00,13687.76,13750.00,13620.01,13722.47,52.257108,2018-01-01 06:44:59.999000+00:00,7.143783e+05,997,20.579891,2.814531e+05,15m,2018,1,1,1,34.71,0.002536,129.99
37,2018-01-01 06:45:00+00:00,13722.48,13800.00,13702.10,13780.41,54.765813,2018-01-01 06:59:59.999000+00:00,7.535164e+05,937,24.814391,3.414476e+05,15m,2018,1,1,1,57.93,0.004222,97.90
38,2018-01-01 07:00:00+00:00,13780.00,13818.55,13555.02,13570.35,292.188777,2018-01-01 07:59:59.999000+00:00,4.002026e+06,4340,147.150029,2.016275e+06,1h,2018,1,1,1,-209.65,-0.015214,263.53
39,2018-01-01 07:00:00+00:00,13780.00,13818.55,13670.00,13775.00,84.038319,2018-01-01 07:14:59.999000+00:00,1.157374e+06,1319,42.535515,5.858475e+05,15m,2018,1,1,1,-5.00,-0.000363,148.55
40,2018-01-01 07:15:00+00:00,13774.99,13775.99,13600.00,13698.00,74.453320,2018-01-01 07:29:59.999000+00:00,1.019043e+06,1312,41.686674,5.707639e+05,15m,2018,1,1,1,-76.99,-0.005589,175.99
41,2018-01-01 07:30:00+00:00,13698.00,13775.00,13590.00,13644.95,89.776654,2018-01-01 07:44:59.999000+00:00,1.228408e+06,895,41.665985,5.703255e+05,15m,2018,1,1,1,-53.05,-0.003873,185.00
42,2018-01-01 07:45:00+00:00,13644.97,13659.97,13555.02,13570.35,43.920484,2018-01-01 07:59:59.999000+00:00,5.972011e+05,814,21.261855,2.893379e+05,15m,2018,1,1,1,-74.62,-0.005469,104.95
43,2018-01-01 08:00:00+00:00,13569.98,13735.24,13400.00,13499.99,271.813553,2018-01-01 08:59:59.999000+00:00,3.681944e+06,3733,122.809696,1.664737e+06,1h,2018,1,1,1,-69.99,-0.005158,335.24
44,2018-01-01 08:00:00+00:00,13569.98,13735.24,13001.13,13220.56,1319.755931,2018-01-01 11:59:59.999000+00:00,1.765121e+07,17200,582.668293,7.792109e+06,4h,2018,1,1,1,-349.42,-0.025749,734.11
45,2018-01-01 08:00:00+00:00,13569.98,13665.00,13520.00,13656.23,58.542067,2018-01-01 08:14:59.999000+00:00,7.948098e+05,919,20.562018,2.791373e+05,15m,2018,1,1,1,86.25,0.006356,145.00
46,2018-01-01 08:15:00+00:00,13656.23,13735.24,13610.27,13632.89,58.900513,2018-01-01 08:29:59.999000+00:00,8.054309e+05,869,34.862743,4.767699e+05,15m,2018,1,1,1,-23.34,-0.001709,124.97
47,2018-01-01 08:30:00+00:00,13614.33,13649.96,13400.00,13434.71,104.766871,2018-01-01 08:44:59.999000+00:00,1.413295e+06,1204,46.829395,6.318254e+05,15m,2018,1,1,1,-179.62,-0.013193,249.96
48,2018-01-01 08:45:00+00:00,13415.00,13508.69,13414.76,13499.99,49.604102,2018-01-01 08:59:59.999000+00:00,6.684083e+05,741,20.555540,2.770044e+05,15m,2018,1,1,1,84.99,0.006335,93.93
49,2018-01-01 09:00:00+00:00,13499.97,13599.98,13459.11,13589.83,55.827255,2018-01-01 09:14:59.999000+00:00,7.554221e+05,825,24.819559,3.360020e+05,15m,2018,1,1,1,89.86,0.006656,140.87

# trend

In [ ]:
# Trend Direction
df['trend_direction'] = np.where(df['price_change'] > 0, 1, -1)

In [ ]:
# Trend Streak
df['trend_streak'] = (df['trend_direction'] != df['trend_direction'].shift()).cumsum()

In [ ]:
# Trend Length
df['trend_length'] = df.groupby('trend_streak').cumcount() + 1

In [ ]:
# Trend Strength
df['trend_strength'] = np.where(
    df['Close'] != 0,
    (df['price_change'] / df['Close']) * df['Volume'],
    0
)

In [ ]:
df.head(10)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,...,month,day,quarter,price_change,return_pct,volatility,trend_direction,trend_streak,trend_length,trend_strength
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,...,1,1,1,-186.64,-0.013608,315.64,-1,1,1,-6.116338
1,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,...,1,1,1,-335.65,-0.024472,1068.55,-1,1,2,-215.987911
2,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,...,1,1,1,-305.62,-0.022283,560.27,-1,1,3,-38.201385
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,...,1,1,1,-159.50,-0.011629,315.64,-1,1,4,-1.454451
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,...,1,1,1,-12.63,-0.000933,148.87,-1,1,5,-0.091669
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,...,1,1,1,-29.59,-0.002192,95.37,-1,1,6,-0.175523
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,...,1,1,1,34.36,0.002546,240.87,1,2,1,0.359879
7,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,...,1,1,1,-325.93,-0.024091,440.51,-1,3,1,-9.471923
8,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,...,1,1,1,-83.36,-0.006162,169.46,-1,3,2,-0.449717
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,...,1,1,1,90.01,0.006682,150.26,1,4,1,0.583218

# volume & market activity

In [ ]:
# Buy Volume
df = df.rename(columns={'Taker buy base asset volume': 'buy_volume'})

In [ ]:
# Sell Volume
df['sell_volume'] = df['Volume'] - df['buy_volume']

In [ ]:
# Buy Ratio
df['buy_ratio'] = np.where(
    df['Volume'] != 0,
    df['buy_volume'] / df['Volume'],
    0
)

In [ ]:
# Sell Ratio
df['sell_ratio'] = np.where(
    df['Volume'] != 0,
    df['sell_volume'] / df['Volume'],
    0
)

In [ ]:
# Net Order Flow
df['order_flow'] = df['buy_volume'] - df['sell_volume']

In [ ]:
# Capital Flow
df.rename(columns={'Quote asset volume': 'capital_flow'}, inplace=True)

In [ ]:
#trade activity
df.rename(columns={'Number of trades': 'trade_activity'}, inplace=True)

In [ ]:
df.head(10)

,Open time,Open,High,Low,Close,Volume,Close time,capital_flow,trade_activity,buy_volume,...,return_pct,volatility,trend_direction,trend_streak,trend_length,trend_strength,sell_volume,buy_ratio,sell_ratio,order_flow
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,...,-0.013608,315.64,-1,1,1,-6.116338,214.834278,0.515436,0.484564,13.687643
1,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,...,-0.024472,1068.55,-1,1,2,-215.987911,4647.976898,0.460160,0.539840,-686.037952
2,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,...,-0.022283,560.27,-1,1,3,-38.201385,936.686141,0.441186,0.558814,-197.167475
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,...,-0.011629,315.64,-1,1,4,-1.454451,60.388880,0.511480,0.488520,2.838253
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,...,-0.000933,148.87,-1,1,5,-0.091669,50.450041,0.485919,0.514081,-2.763652
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,...,-0.002192,95.37,-1,1,6,-0.175523,36.193631,0.547036,0.452964,7.516775
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,...,0.002546,240.87,1,2,1,0.359879,67.801726,0.521511,0.478489,6.096267
7,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,...,-0.024091,440.51,-1,3,1,-9.471923,202.856603,0.471310,0.528690,-22.016200
8,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,...,-0.006162,169.46,-1,3,2,-0.449717,38.279881,0.472275,0.527725,-4.022229
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,...,0.006682,150.26,1,4,1,0.583218,42.725801,0.513716,0.486284,2.410156

#support & resistance

In [ ]:
df['support'] = df['Close'] - df['Low']
df['resistance'] = df['High'] - df['Close']

In [ ]:
df.head(10)

,Open time,Open,High,Low,Close,Volume,Close time,capital_flow,trade_activity,buy_volume,...,trend_direction,trend_streak,trend_length,trend_strength,sell_volume,buy_ratio,sell_ratio,order_flow,support,resistance
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,...,-1,1,1,-6.116338,214.834278,0.515436,0.484564,13.687643,129.00,186.64
1,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,...,-1,1,2,-215.987911,4647.976898,0.460160,0.539840,-686.037952,630.00,438.55
2,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,...,-1,1,3,-38.201385,936.686141,0.441186,0.558814,-197.167475,254.65,305.62
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,...,-1,1,4,-1.454451,60.388880,0.511480,0.488520,2.838253,156.14,159.50
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,...,-1,1,5,-0.091669,50.450041,0.485919,0.514081,-2.763652,119.12,29.75
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,...,-1,1,6,-0.175523,36.193631,0.547036,0.452964,7.516775,20.41,74.96
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,...,1,2,1,0.359879,67.801726,0.521511,0.478489,6.096267,79.01,161.86
7,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,...,-1,3,1,-9.471923,202.856603,0.471310,0.528690,-22.016200,47.68,392.83
8,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,...,-1,3,2,-0.449717,38.279881,0.472275,0.527725,-4.022229,43.35,126.11
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,...,1,4,1,0.583218,42.725801,0.513716,0.486284,2.410156,114.37,35.89

# Averages

In [ ]:
df['avg_volume_20'] = df['Volume'].rolling(20).mean()
df['avg_volatility_20'] = df['volatility'].rolling(20).mean()

#breaout up and down

In [ ]:
df['rolling_high_20'] = df['High'].rolling(20).max().shift(1)
df['rolling_low_20'] = df['Low'].rolling(20).min().shift(1)

In [ ]:
df['breakout_up'] = np.where(
    (df['Close'] > df['rolling_high_20']) &
    (df['Volume'] > df['avg_volume_20']),
    1, 0
)

In [ ]:
df['breakout_down'] = np.where(
    (df['Close'] < df['rolling_low_20']) &
    (df['Volume'] > df['avg_volume_20']),
    1, 0
)

#market behavior

In [ ]:
#high volatility
df['high_volatility'] = np.where(
    df['volatility'] > df['avg_volatility_20'],
    1, 0
)

In [ ]:
#compression
df['compression'] = np.where(
    (df['volatility'] < df['avg_volatility_20'] * 0.5) &
    (df['Volume'] < df['avg_volume_20']),
    1, 0
)

In [ ]:
#volume spike
df['volume_spike'] = np.where(
    (df['Volume'] > df['avg_volume_20'] * 1.5) &
    (df['return_pct'].abs() > 0.01),
    1, 0
)

In [ ]:
#overheating
df['overheating'] = np.where(
    (df['buy_ratio'] > 0.6) &
    (df['Volume'] > df['avg_volume_20'] * 1.5) &
    (df['return_pct'] > 0),
    1, 0
)

In [ ]:
#whale activity
df['whale_activity'] = np.where(
    df['Volume'] > df['Volume'].quantile(0.95),
    1, 0
)

#check&load

In [ ]:
df.isna().sum().sort_values(ascending=False)

rolling_high_20                 20
rolling_low_20                  20
avg_volatility_20               19
avg_volume_20                   19
Open time                        0
Open                             0
High                             0
Low                              0
capital_flow                     0
Close time                       0
Volume                           0
Close                            0
trade_activity                   0
buy_volume                       0
Taker buy quote asset volume     0
timeframe                        0
price_change                     0
return_pct                       0
volatility                       0
trend_direction                  0
year                             0
month                            0
day                              0
quarter                          0
sell_volume                      0
trend_strength                   0
trend_length                     0
trend_streak                     0
support                          0
order_flow                       0
sell_ratio                       0
buy_ratio                        0
resistance                       0
breakout_up                      0
breakout_down                    0
high_volatility                  0
compression                      0
volume_spike                     0
overheating                      0
whale_activity                   0
dtype: int64

In [ ]:
df[df.isna().any(axis=1)].head(50)

,Open time,Open,High,Low,Close,Volume,Close time,capital_flow,trade_activity,buy_volume,...,avg_volatility_20,rolling_high_20,rolling_low_20,breakout_up,breakout_down,high_volatility,compression,volume_spike,overheating,whale_activity
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,...,NaN,NaN,NaN,0,0,0,0,0,0,0
1,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,...,NaN,NaN,NaN,0,0,0,0,0,0,1
2,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,...,NaN,NaN,NaN,0,0,0,0,0,0,0
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,...,NaN,NaN,NaN,0,0,0,0,0,0,0
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,...,NaN,NaN,NaN,0,0,0,0,0,0,0
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,...,NaN,NaN,NaN,0,0,0,0,0,0,0
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,...,NaN,NaN,NaN,0,0,0,0,0,0,0
7,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,...,NaN,NaN,NaN,0,0,0,0,0,0,0
8,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,...,NaN,NaN,NaN,0,0,0,0,0,0,0
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,...,NaN,NaN,NaN,0,0,0,0,0,0,0
10,2018-01-01 01:30:00+00:00,13559.99,13559.99,13430.00,13440.01,74.368405,2018-01-01 01:44:59.999000+00:00,1.004038e+06,1047,38.653471,...,NaN,NaN,NaN,0,0,0,0,0,0,0
11,2018-01-01 01:45:00+00:00,13440.01,13440.01,13155.38,13203.06,148.929310,2018-01-01 01:59:59.999000+00:00,1.982724e+06,1650,62.793323,...,NaN,NaN,NaN,0,0,0,0,0,0,0
12,2018-01-01 02:00:00+00:00,13203.00,13411.76,13202.03,13387.00,108.542470,2018-01-01 02:14:59.999000+00:00,1.446924e+06,1528,40.703069,...,NaN,NaN,NaN,0,0,0,0,0,0,0
13,2018-01-01 02:00:00+00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999000+00:00,5.710192e+06,4887,192.237935,...,NaN,NaN,NaN,0,0,0,0,0,0,0
14,2018-01-01 02:15:00+00:00,13387.00,13388.00,13225.00,13225.00,95.186039,2018-01-01 02:29:59.999000+00:00,1.265431e+06,1079,43.068838,...,NaN,NaN,NaN,0,0,0,0,0,0,0
15,2018-01-01 02:30:00+00:00,13247.80,13349.99,13200.00,13321.08,111.719503,2018-01-01 02:44:59.999000+00:00,1.483295e+06,1074,53.247854,...,NaN,NaN,NaN,0,0,0,0,0,0,0
16,2018-01-01 02:45:00+00:00,13338.97,13418.43,13260.09,13330.18,113.616560,2018-01-01 02:59:59.999000+00:00,1.514541e+06,1206,55.218174,...,NaN,NaN,NaN,0,0,0,0,0,0,0
17,2018-01-01 03:00:00+00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999000+00:00,5.657448e+06,4789,137.918407,...,NaN,NaN,NaN,0,0,0,0,0,0,0
18,2018-01-01 03:00:00+00:00,13330.26,13450.76,13290.00,13444.99,89.019514,2018-01-01 03:14:59.999000+00:00,1.189070e+06,1070,35.514692,...,NaN,NaN,NaN,0,0,0,0,0,0,0
19,2018-01-01 03:15:00+00:00,13440.00,13611.27,13440.00,13562.37,112.273306,2018-01-01 03:29:59.999000+00:00,1.516663e+06,1415,43.355251,...,273.6425,NaN,NaN,0,0,0,0,0,0,0

In [ ]:
# Remove initial rows affected by rolling calculations (NaN period)
df = df.iloc[50:].reset_index(drop=True)

In [ ]:
df.head(10)

,Open time,Open,High,Low,Close,Volume,Close time,capital_flow,trade_activity,buy_volume,...,avg_volatility_20,rolling_high_20,rolling_low_20,breakout_up,breakout_down,high_volatility,compression,volume_spike,overheating,whale_activity
0,2018-01-01 09:00:00+00:00,13499.97,13670.00,13459.11,13616.99,213.095829,2018-01-01 09:59:59.999000+00:00,2.893105e+06,3128,96.470199,...,192.7815,13818.55,13001.13,0,0,1,0,0,0,0
1,2018-01-01 09:15:00+00:00,13556.88,13650.00,13531.19,13549.77,55.580387,2018-01-01 09:29:59.999000+00:00,7.552835e+05,826,27.737784,...,193.7720,13818.55,13001.13,0,0,0,0,0,0,0
2,2018-01-01 09:30:00+00:00,13531.82,13610.00,13510.01,13599.99,50.137197,2018-01-01 09:44:59.999000+00:00,6.803677e+05,696,20.799501,...,195.0965,13818.55,13001.13,0,0,0,0,0,0,0
3,2018-01-01 09:45:00+00:00,13599.99,13670.00,13571.33,13616.99,51.550990,2018-01-01 09:59:59.999000+00:00,7.020316e+05,781,23.113355,...,196.9485,13818.55,13001.13,0,0,0,0,0,0,0
4,2018-01-01 10:00:00+00:00,13632.00,13657.92,13540.33,13550.00,50.432284,2018-01-01 10:14:59.999000+00:00,6.851597e+05,790,17.409453,...,188.3280,13818.55,13001.13,0,0,0,0,0,0,0
5,2018-01-01 10:00:00+00:00,13632.00,13657.92,13497.98,13570.01,169.512196,2018-01-01 10:59:59.999000+00:00,2.298369e+06,2769,68.490957,...,186.7940,13818.55,13001.13,0,0,0,0,0,0,0
6,2018-01-01 10:15:00+00:00,13550.00,13560.98,13497.98,13549.03,47.520692,2018-01-01 10:29:59.999000+00:00,6.429499e+05,691,25.134436,...,183.4445,13818.55,13001.13,0,0,0,1,0,0,0
7,2018-01-01 10:30:00+00:00,13548.35,13603.77,13515.12,13586.51,43.999806,2018-01-01 10:44:59.999000+00:00,5.965490e+05,681,13.863250,...,182.9820,13818.55,13001.13,0,0,0,1,0,0,0
8,2018-01-01 10:45:00+00:00,13585.91,13590.88,13515.14,13570.01,27.559414,2018-01-01 10:59:59.999000+00:00,3.737101e+05,607,12.083818,...,173.5925,13818.55,13001.13,0,0,0,1,0,0,0
9,2018-01-01 11:00:00+00:00,13573.00,13589.89,13150.00,13251.76,214.320181,2018-01-01 11:14:59.999000+00:00,2.847521e+06,2325,71.788942,...,188.1595,13818.55,13001.13,0,0,1,0,0,0,0

In [ ]:
cols_to_keep = [

# Time
'Open time','timeframe',
'year','quarter','month','day',

# Price data
'Open','High','Low','Close',
'price_change','return_pct','volatility',

# Volume & market activity
'Volume','capital_flow','trade_activity',
'buy_volume','sell_volume',
'buy_ratio','sell_ratio','order_flow',

# Trend KPIs
'trend_direction','trend_length','trend_strength',

# Market behavior signals
'volume_spike',
'high_volatility',
'compression',
'overheating',
'whale_activity',

# Breakouts
'breakout_up',
'breakout_down',

# Support & resistance
'support',
'resistance'
]

In [ ]:
df_final = df[cols_to_keep]

In [ ]:
df_final.head(5)

,Open time,timeframe,year,quarter,month,day,Open,High,Low,Close,...,trend_strength,volume_spike,high_volatility,compression,overheating,whale_activity,breakout_up,breakout_down,support,resistance
0,2018-01-01 09:00:00+00:00,1h,2018,1,1,1,13499.97,13670.00,13459.11,13616.99,...,1.831277,0,1,0,0,0,0,0,157.88,53.01
1,2018-01-01 09:15:00+00:00,15m,2018,1,1,1,13556.88,13650.00,13531.19,13549.77,...,-0.029165,0,0,0,0,0,0,0,18.58,100.23
2,2018-01-01 09:30:00+00:00,15m,2018,1,1,1,13531.82,13610.00,13510.01,13599.99,...,0.251313,0,0,0,0,0,0,0,89.98,10.01
3,2018-01-01 09:45:00+00:00,15m,2018,1,1,1,13599.99,13670.00,13571.33,13616.99,...,0.064358,0,0,0,0,0,0,0,45.66,53.01
4,2018-01-01 10:00:00+00:00,15m,2018,1,1,1,13632.00,13657.92,13540.33,13550.00,...,-0.305199,0,0,0,0,0,0,0,9.67,107.92

In [ ]:
df_final.to_csv("bitcoin_kpis.csv", index=False)